name: TestRunner
on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Enter the cucumber tags:'
        required: true

jobs:
  execution:
    name: Build and Execute Tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout Source
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build and Execute Test
        run: mvn test -Dcucumber.options="--tags {{ github.event.inputs.tags }}"

